### ISSUE TITLE
运行了 GetImgTool.py  然后怎么获取坐标

### ISSUE THREAD

**Issue by gl09025** [Skyexu/TopSup#107]
![screen shot 2018-01-15 at 16 02 25](https://user-images.githubusercontent.com/18009385/34932384-992d01e2-fa0d-11e7-9b28-da058b1e0810.png)
运行之后怎么获取左上角坐标和右下角坐标

**Comment by cncal** [comment]
点击放大镜图标，将鼠标悬停在图片上，在右下角可以看到 x、y 轴坐标
