### ISSUE TITLE
求问，运行GetQuestionAndroid.py时候报错ModuleNotFoundError: No module named 'aip

### ISSUE THREAD

**Issue by DrMio** [Skyexu/TopSup#126]
File "C:\Users\Milo\Desktop\TopSup-master\GetQuestionAndroid.py", line 9, in <module>
    from common import screenshot, ocr, methods
  File "C:\Users\Milo\Desktop\TopSup-master\common\ocr.py", line 10, in <module>
    from aip import AipOcr
ModuleNotFoundError: No module named 'aip'
不知道该怎么处理。
使用python3 和python2.7都是这个错误。
是Python萌新QAQ

**Comment by DrMio** [comment]
https://github.com/aeroxis/sultan/issues/40
根据这个问题的答案我尝试了一下，依然报错如上。
pip version：pip 9.0.1（python 3.6）
pillow == 5.0.0
pytesseract == 0.1.7
sultan == 0.7.0
which python无法运行

**Comment by Skyexu** [comment]
@DrMio pip install baidu-aip

**Comment by DrMio** [comment]
了解。还有一个报错ModuleNotFoundError: No module named 'colorama'
不知道该怎么处理。

**Comment by Skyexu** [comment]
*{
        margin: 0;
        padding: 0;
    }
    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
pip install colorama   ，其实报错信息已经说了是什么原因啦，包没有安装



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    



    在2018年1月18日 12:59，DrMio<notifications@github.com> 写道： 


了解。还有一个报错ModuleNotFoundError: No module named 'colorama'
不知道该怎么处理。

**Comment by DrMio** [comment]
这样！谢谢啦~已经搞定了！
