### ISSUE TITLE
能不能后台打开百度？

### ISSUE THREAD

**Issue by tangxiadi** [Skyexu/TopSup#129]
能不能后台打开百度？直接调用IE打开百度，等打开IE答题时间早完了。。。

**Comment by tangxiadi** [comment]
比如用curl命令得到html元素，直接分析整个html内4个答案各有多少个，数量最多的一般就是答案

**Comment by Skyexu** [comment]
@tangxiadi 这个已经做了，请看 readme 有三个方法。打开浏览器的是为了自己参考搜索结果，数量最多也不一定对

**Comment by tangxiadi** [comment]
@Skyexu 原来是我误将默认浏览器设置成了IE，我以为代码故意调用的IE呢。

**Comment by tangxiadi** [comment]
对于方法二和方法三，建议可以加段否定词判断的代码进去，参考 https://github.com/Allen-Liang/answer_the_question
程序默认应该是肯定题选绿、否定题选红吧？但是这样还需要自己去判断语句，就增加了思考时间。建议可以根据肯定或者否定语气，直接在后面输出建议选择某某答案。

**Comment by Skyexu** [comment]
@tangxiadi 你好，多谢建议。其实没加这个是怕否定词没有完全覆盖，推荐的答案出错，自己去思考避免这个问题。这个项目也是简单做了一下，拿来答题的话，时间上有时也不一定能来得及。明天我优化一下，加上去吧
