### ISSUE TITLE
可以改成常驻么？不要每次执行完了就关闭进程

### ISSUE THREAD

**Issue by luanwulin** [Skyexu/TopSup#15]
每次重新运行都要耗时间，一直常驻，按回车或者别的，开始新的一次检测可以么？

还有就是感觉时间都花到截图上面去了，有优化的空间么？

**Comment by asseywang** [comment]
应该有，我看隔壁https://github.com/se4/cddh 这个程序的adb截图就快很多。但是没搞清为啥同样原理他那个快。

**Comment by Skyexu** [comment]
@luanwulin 谢谢，已更新优化
