### ISSUE TITLE
给点建议, 加个chrome插件来筛选答案,  3个答案，3个窗口

### ISSUE THREAD

**Issue by binlaniua** [Skyexu/TopSup#19]
一个问题 + 一个答案  = 一个搜索窗口(配合chrome插件做, 非答案文件全部隐藏，答案字体放大，加粗)

**Comment by binlaniua** [comment]
想了下，不用3个窗口了，1个窗口，3个答案，不同高亮规则就可以了。

**Comment by binlaniua** [comment]
![image](https://user-images.githubusercontent.com/5960462/34767086-3a2834f2-f632-11e7-82de-4bf8db14887f.png)
插件已做好，等开局试试效果

**Comment by binlaniua** [comment]
![image](https://user-images.githubusercontent.com/5960462/34767126-4f933828-f632-11e7-90be-5c07caae875e.png)

**Comment by ljfyuyu** [comment]
厉害了，大神
