### ISSUE TITLE
总是提示没有权限

### ISSUE THREAD

**Issue by acdxxx177** [Skyexu/TopSup#60]
我在win10和win7两台电脑上有运行过，为什么总出现下面的错误，有解决办法吗？
python 3.6使用的是项目里连接安装版tessdata，目录都配置好了

运行python GetQuestionTessAndroid.py
> 采用方式 2 获取截图
> Traceback (most recent call last):
>   File "GetQuestionTessAndroid.py", line 20, in <module>
>     question, choices = ocr.ocr_img(img)
>   File "D:\TopSup-master\common\ocr.py", line 76, in ocr_img
>   question = pytesseract.image_to_string(question_im, lang='chi_sim', config=tessdata_dir_config)
>   File "C:\Users\Designer\AppData\Local\Programs\Python\Python36\lib\site-packag
> es\pytesseract\pytesseract.py", line 122, in image_to_stringconfig=config)
>   File "C:\Users\Designer\AppData\Local\Programs\Python\Python36\lib\site-packag
> es\pytesseract\pytesseract.py", line 46, in run_tesseract
>     proc = subprocess.Popen(command, stderr=subprocess.PIPE)
>   File "C:\Users\Designer\AppData\Local\Programs\Python\Python36\lib\subprocess.
> py", line 709, in __init__
>     restore_signals, start_new_session)
>   File "C:\Users\Designer\AppData\Local\Programs\Python\Python36\lib\subprocess.
> py", line 997, in _execute_child
>     startupinfo)
> PermissionError: [WinError 5] 拒绝访问。

运行python GetImgTool.py

> Traceback (most recent call last):
>   File "GetImgTool.py", line 10, in <module>
>     import matplotlib.pyplot as plt
> ModuleNotFoundError: No module named 'matplotlib'

**Comment by free46000** [comment]
PermissionError 这个问题可以尝试以管理员身份运行打开cmd ，在执行命令试试

**Comment by Chzhewen** [comment]
ocr.py 中 配置 tesseract 路径，需要路径+tesseract.exe。如C:\\Program Files (x86)\\Tesseract-OCR\\tesseract.exe这样试试。
